In [2]:
import pandas as pd
from pandas import Series, DataFrame

In [38]:
# Series
# Series是⼀种类似于⼀维数组的对象，它由⼀组数据（各种NumPy数据类型）
# 以及⼀组与之相关的数据标签（即索引）组成
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
# 可以通过Series 的values和index属性 获取其数组表示形式和索引对象
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
# 通常，我们希望所创建的Series带有⼀个可以对各个数据点进⾏ 标记的索引
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [15]:
obj2['a']

-5

In [17]:
obj2['d']=6
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [18]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [19]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [20]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [21]:
'b' in obj2

True

In [13]:
# 回顾一下numpy
import numpy as np
xxx = np.arange(10)
xxx

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
xxx[2]

2

In [22]:
# 如果数据被存放在⼀个Python字典中，也可以直接通过这个字典 来创建Series
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
# 如果只传⼊⼀个字典，则结果Series中的索引就是原字典的键 （有序排列）
# 你可以传⼊排好序的字典的键以改变顺序
states = ['California','Texas','Ohio','Oregon']
obj4 = pd.Series(sdata,index=states)
obj4
# 由于"California"所对应的sdata值找不到，所以其结果就为NaN（即“⾮数字”（not a number）
# 在 pandas中，它⽤于表示缺失或NA值）

California        NaN
Texas         71000.0
Ohio          35000.0
Oregon        16000.0
dtype: float64

In [25]:
# pandas的isnull 和notnull函数可⽤于检测缺失数据
pd.isnull(obj4)

California     True
Texas         False
Ohio          False
Oregon        False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Texas          True
Ohio           True
Oregon         True
dtype: bool

In [27]:
# Series也有类似的实例⽅法
obj4.isnull()

California     True
Texas         False
Ohio          False
Oregon        False
dtype: bool

In [28]:
# Series最重要的⼀个功能是，它会根据运算的索引标签⾃动对⻬数据
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Texas         71000.0
Ohio          35000.0
Oregon        16000.0
dtype: float64

In [30]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [34]:
# Series对象本身及其索引都有⼀个name属性
obj4.name = 'population'
obj4.index.name = 'states'
obj4

states
California        NaN
Texas         71000.0
Ohio          35000.0
Oregon        16000.0
Name: population, dtype: float64

In [39]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [40]:
# Series的索引可以通过赋值的⽅式就地修改
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [41]:
# DataFrame
# DataFrame是⼀个表格型的数据结构，它含有⼀组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）
# DataFrame既有⾏索引也有列索引，它可以被看做由Series组成的字典（共⽤同⼀个索引）
# DataFrame中的数据是以⼀个或多个⼆维块存放的（⽽不是列表、字典或别的⼀维数据结构）
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [42]:
# 对于特别⼤的DataFrame，head⽅法会选取前五⾏
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [43]:
# 如果指定了列序列，则DataFrame的列就会按照指定顺序进⾏排 列
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [44]:
# 如果传⼊的列在数据中找不到，就会在结果中产⽣缺失
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],
                     index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [45]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
# 通过类似字典标记的⽅式或属性的⽅式，可以将DataFrame的列 获取为⼀个Series
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [50]:
frame2.state
# frame2[column]适⽤于任何列的名
# 但是frame2.column只有在列名是⼀个合理的Python变量名时才适⽤。

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [51]:
# ⾏也可以通过位置或名称的⽅式进⾏获取，⽐如⽤loc属性
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [52]:
# 列可以通过赋值的⽅式进⾏修改
frame2['debt']=16
frame2

year   state  pop  debt
one    2000    Ohio  1.5    16
two    2001    Ohio  1.7    16
three  2002    Ohio  3.6    16
four   2001  Nevada  2.4    16
five   2002  Nevada  2.9    16
six    2003  Nevada  3.2    16

In [53]:
# 将列表或数组赋值给某个列时
# 其⻓度必须跟DataFrame的⻓度相匹配
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [54]:
# 如果赋值的是⼀个Series，就会精确匹配DataFrame的索引，所有的空位都将被填上缺失值
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [60]:
# 为不存在的列赋值会创建出⼀个新列
# 先添加⼀个新的布尔值的列，state是否为'Ohio'
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [61]:
# del⽅法可以⽤来删除这列
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [66]:
# 另⼀种常⻅的数据形式是嵌套字典
pop = {'Nevada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7, 2002: 3.6}}
# 如果嵌套字典传给DataFrame，pandas就会被解释为
# 外层字典的键作为列，内层键则作为⾏索引
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [67]:
# 对DataFrame进⾏转置 （交换⾏和列）
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [80]:
pd.DataFrame(frame3, index=[2001, 2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [76]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}
        # =='Nevada':frame3['Nevada'][:-1]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [82]:
# 如果设置了DataFrame的index和columns的name属性，则这些信息也会被显示出来：
frame3.index.name = 'year';frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [83]:
# 跟Series⼀样，values属性也会以⼆维ndarray的形式返回DataFrame中的数据
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [84]:
# 如果DataFrame各列的数据类型不同，则值数组的dtype就会选⽤能兼容所有列的数据类型
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [87]:
# 索引对象 
# 构建Series或DataFrame时，所⽤到的任何数组或其他序列的标签都会被转换成⼀个Index
obj = pd.Series(range(3),index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [88]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [90]:
# Index对象是不可变的，因此⽤户不能对其进⾏修改
index[1]='d' # TypeError 

In [92]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [93]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [94]:
obj2.index is labels

True

In [97]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [98]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [99]:
2003 in frame3.index

False

In [100]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [101]:
'Ohio' in frame3.columns

True

In [102]:
# 与python的集合不同，pandas的Index可以包含重复的标签
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [105]:
# 重新索引 
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [106]:
# pandas对象的⼀个重要⽅法是reindex
# 其作⽤是创建⼀个新对象,它的数据符合新的索引
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [107]:
obj3 = pd.Series(['blue', 'purple', 'yellow'])
obj3

0      blue
1    purple
2    yellow
dtype: object

In [108]:
# 重新索引时可能需要做⼀些插值处理
# method选项即可达到此⽬的，例如
# 使⽤ffill可以实现前向值填充
obj3.reindex(range(6),method='ffill')

0      blue
1    purple
2    yellow
3    yellow
4    yellow
5    yellow
dtype: object

In [109]:
# 借助DataFrame，reindex可以修改（⾏）索引和列。
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a','c','d'],
                    columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [110]:
# 只传递⼀个序列时，会重新索引结果的⾏：
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [111]:
# 列可以⽤columns关键字重新索引
states = ['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [129]:
# 丢弃指定轴上的项
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [131]:
# drop⽅法返回的是⼀个在指定轴上删除了指定值的新对象：
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [119]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio','Colorado','Utah','New York'],
                   columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [120]:
# ⽤标签序列调⽤drop会从⾏标签（axis 0）删除值
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [121]:
# 通过传递axis=1或axis='columns'可以删除列的值
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [123]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [124]:
data.drop(['Ohio'],axis='index')

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [132]:
# ⼩⼼使⽤inplace，它会销毁所有被删除的数据
obj.drop('c',inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [134]:
# 索引、选取和过滤 
# Series的索引值不只是整数
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [135]:
obj['b']

1.0

In [136]:
obj[1]

1.0

In [137]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [139]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [140]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [141]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [142]:
# 利⽤标签的切⽚运算与普通的Python切⽚运算不同，其末端是包含的
obj['b':'c'] 

b    1.0
c    2.0
dtype: float64

In [143]:
# ⽤切⽚可以对Series的相应部分进⾏设置
obj['b':'c']=5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [147]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio','Colorado','Utah','New York'],
                   columns=['one','two','three','four'])
data[['two']]

two
Ohio        1
Colorado    5
Utah        9
New York   13

In [145]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [148]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [149]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [151]:
data < 5 

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [153]:
data[data<5]=0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [154]:
# ⽤loc和iloc进⾏选取 
# 使⽤轴标签（loc）或整数索引（iloc），从DataFrame选择⾏和列的⼦集
# 我们通过标签选择⼀⾏和多列
data.loc['Colorado',['two','three']] 

two      5
three    6
Name: Colorado, dtype: int32

In [155]:
# 然后⽤iloc和整数进⾏选取
data.iloc[2, [3, 0, 1]] 

four    11
one      8
two      9
Name: Utah, dtype: int32

In [156]:
data.iloc[2] 

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [157]:
data.iloc[[1, 2], [3, 0, 1]] 

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [161]:
# 这两个索引函数也适⽤于⼀个标签或多个标签的切⽚
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [162]:
data.iloc[:, :3][data.three > 5] 

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [166]:
# 整数索引
ser = pd.Series(np.arange(3.)) 
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [168]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])
ser2[-1]

2.0

In [169]:
# 如果轴索引含有整数，数据选取总会使⽤标签
# 为了更准确，请使⽤loc（标签）或iloc（整数） 
ser[:1] 

0    0.0
dtype: float64

In [170]:
ser.loc[:1] 

0    0.0
1    1.0
dtype: float64

In [171]:
ser.iloc[:1] 

0    0.0
dtype: float64

In [172]:
# 算术运算和数据对⻬ 
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [173]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [174]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [175]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),
                   columns=list('bcd'),
                  index=['Ohio','Texas','Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),
                   columns=list('bde'),
                  index=['Utah','Ohio','Texas','Qregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [176]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Qregon  9.0  10.0  11.0

In [177]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Qregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [178]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1

A
0  1
1  2

In [179]:
df2

B
0  3
1  4

In [180]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [189]:
# 在算术⽅法中填充值 
df1=pd.DataFrame(np.arange(12.).reshape((3, 4)),columns=list('abcd'))
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))
df2.loc[1,'b']=np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [190]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [191]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [192]:
# 使⽤df1的add⽅法，传⼊df2以及⼀个fill_value参数
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [194]:
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [195]:
df1.rdiv(1) 

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [ ]:
P205